POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Blogging is so 2000s",
    "author": "Bloggy Blogger",
    "url": "http://www.aintarealthang.com",
    "likes": 12
}