POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NDNiMDQwMmNhNWRjNTAwYTAzZjMwYzEiLCJpYXQiOjE2ODE2NzYxMTJ9.2eBknxjfK2EMvDDUaWCWB_VCQKBc84LPtpWwVH7Y6Fg

{
    "title": "Ninth blog",
    "author": "Blogster Prime",
    "url": "http://greatblogtakefour.com",
    "likes": 9,
    "userId": "643b0402ca5dc500a03f30c1"
}