POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Another blog",
    "author": "Bloggy Blogger",
    "url": "http://nicestblogaround.com",
    "likes": 2,
    "userId": "643ab9ed4ea5ad3315669937"
}